kafka:
  broker:
    replicaCount: 3

elasticsearch:
  master:
    replicaCount: 3
  data:
    replicaCount: 3
  coordinating:
    replicaCount: 3
  ingest:
    replicaCount: 3

postgresql:
  postgresql:
    auth:
      postgresPassword: "your-secure-postgres-password"
      username: "ecommerce_user"
      password: "your-app-password"
      database: "ecommerce_analytics"
    primary:
      persistence:
        size: 8Gi

fluentd:
  aggregator:
    resources:
      limits:
        cpu: 500m
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi

metabase:
  replicaCount: 3